/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package A1_Gradle;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println("HelloWOrls");
        return true;
    }
}
